--[[
	BetterRep (C) Kruithne <kruithne@gmail.com>
	Licensed under GNU General Public Licence version 3.
	
	https://github.com/Kruithne/BetterRep

	BetterRepData.lua - Defines data used in BetterRep.
]]

local B = BetterRep;
local L = BetterRep.L; -- Localization.

local EXPANSION_VANILLA = 1;
local EXPANSION_TBC = 2;
local EXPANSION_WRATH = 3;
local EXPANSION_CATA = 4;
local EXPANSION_MISTS = 5;
local EXPANSION_WARLORDS = 6;
local EXPANSION_LEGION = 7;

B.Expansions = {
	[EXPANSION_VANILLA] = {
		["name"] = L.EXPANSION_VANILLA,
		["buttonTexture"] = [[Interface\ENCOUNTERJOURNAL\UI-EJ-DUNGEONBUTTON-Deadmines]],
		["header"] = {
			["texture"] = [[Interface\GLUES\LOADINGSCREENS\LoadScreenDeadmines]],
			["offset"] = 0.56,
			["offsetFactor"] = 0.1,
		},
	},

	[EXPANSION_TBC] = {
		["name"] = L.EXPANSION_TBC,
		["buttonTexture"] = [[Interface\ENCOUNTERJOURNAL\UI-EJ-DUNGEONBUTTON-SunwellPlateau]],
		["header"] = {
			["texture"] = [[Interface\GLUES\LOADINGSCREENS\LOADSCREENAUCHINDOUN]],
			["offset"] = 0.4,
			["offsetFactor"] = 0.1,
		},
	},

	[EXPANSION_WRATH] = {
		["name"] = L.EXPANSION_WOTLK,
		["buttonTexture"] = [[Interface\ENCOUNTERJOURNAL\UI-EJ-DUNGEONBUTTON-PitofSaron]],
		["header"] = {
			["texture"] = [[Interface\GLUES\LOADINGSCREENS\LoadScreenPitofSaron]],
			["offset"] = 0.35,
			["offsetFactor"] = 0.1,
		},
	},

	[EXPANSION_CATA] = {
		["name"] = L.EXPANSION_CATA,
		["buttonTexture"] = [[Interface\ENCOUNTERJOURNAL\UI-EJ-DUNGEONBUTTON-Firelands1]],
		["header"] = {
			["texture"] = [[Interface\GLUES\LOADINGSCREENS\LoadScreenDeepholmDungeon]],
			["offset"] = 0.6,
			["offsetFactor"] = 0.1,
		},
	},

	[EXPANSION_MISTS] = {
		["name"] = L.EXPANSION_MISTS,
		["buttonTexture"] = [[Interface\ENCOUNTERJOURNAL\UI-EJ-DUNGEONBUTTON-Pandaria]],
		["header"] = {
			["texture"] = [[Interface\GLUES\LOADINGSCREENS\LoadScreen_GoldRush]],
			["offset"] = 0.6,
			["offsetFactor"] = 0.1,
		},
	},

	[EXPANSION_WARLORDS] = {
		["name"] = L.EXPANSION_WARLORDS,
		["buttonTexture"] = [[Interface\ENCOUNTERJOURNAL\UI-EJ-DUNGEONBUTTON-GrimrailDepot]],
		["header"] = {
			["texture"] = [[Interface\GLUES\LOADINGSCREENS\LoadScreenOgreCompound]],
			["offset"] = 0.5,
			["offsetFactor"] = 0.1,
		},
	},

	[EXPANSION_LEGION] = {
		["name"] = L.EXPANSION_LEGION,
		["buttonTexture"] = [[Interface\ENCOUNTERJOURNAL\UI-EJ-DUNGEONBUTTON-VaultoftheWardens]],
		["header"] = {
			["texture"] = [[Interface\GLUES\LOADINGSCREENS\loadingscreen_mardumwide]],
			["offset"] = 0.6,
			["offsetFactor"] = 0.2,
		},
	},
};

local REACT_NEUTRAL = "Neutral";
local REACT_ALLIANCE = "Alliance";
local REACT_HORDE = "Horde";

B.Factions = {
	[EXPANSION_VANILLA] = {
		[REACT_NEUTRAL] = {
			[21] = L.FACTION_BOOTY_BAY,
			[59] = L.FACTION_THORIUM_BROTHERHOOD,
			[70] = L.FACTION_SYNDICATE,
			[87] = L.FACTION_BLOODSAIL_BUCCANEERS,
			[92] = L.FACTION_GELKIS_CLAN_CENTAUR,
			[93] = L.FACTION_MAGRAM_CLAN_CENTAUR,
			[270] = L.FACTION_ZANDALAR_TRIBE,
			[349] = L.FACTION_RAVENHOLDT,
			[369] = L.FACTION_GADGETZAN,
			[470] = L.FACTION_RATCHET,
			[529] = L.FACTION_ARGENT_DAWN,
			[576] = L.FACTION_TIMBERMAW_HOLD,
			[577] = L.FACTION_EVERLOOK,
			[609] = L.FACTION_CENARION_CIRCLE,
			[749] = L.FACTION_HYDRAXIAN_WATERLORDS,
			[809] = L.FACTION_SHENDRALAR,
			[909] = L.FACTION_DARKMOON_FAIRE,
			[910] = L.FACTION_BROOD_OF_NOZDORMU,
		},
		[REACT_ALLIANCE] = {
			[47] = L.FACTION_IRONFORGE,
			[54] = L.FACTION_GNOMEREGAN,
			[69] = L.FACTION_DARNASSUS,
			[72] = L.FACTION_STORMWIND,
			[509] = L.FACTION_THE_LEAGUE_OF_ARATHOR,
			[589] = L.FACTION_WINTERSABER_TRAINERS,
			[730] = L.FACTION_STORMPIKE_GUARD,
			[890] = L.FACTION_SILVERWING_SENTINELS,
		},
		[REACT_HORDE] = {
			[68] = L.FACTION_UNDERCITY,
			[76] = L.FACTION_ORGRIMMAR,
			[81] = L.FACTION_THUNDER_BLUFF,
			[510] = L.FACTION_THE_DEFILERS,
			[530] = L.FACTION_DARKSPEAR_TROLLS,
			[729] = L.FACTION_FROSTWOLF_CLAN,
			[889] = L.FACTION_WARSONG_OUTRIDERS,
		},
	},
	[EXPANSION_TBC] = {
		[REACT_HORDE] = {
			[911] = L.FACTION_SILVERMOON_CITY,
			[922] = L.FACTION_TRANQUILLIEN,
			[941] = L.FACTION_THE_MAGHAR,
			[947] = L.FACTION_THRALLMAR,
		},
		[REACT_ALLIANCE] = {
			[930] = L.FACTION_EXODAR,
			[946] = L.FACTION_HONOR_HOLD,
			[978] = L.FACTION_KURENAI,
			[1037] = L.FACTION_ALLIANCE_VANGUARD,
		},
		[REACT_NEUTRAL] = {
			[932] = L.FACTION_THE_ALDOR,
			[933] = L.FACTION_THE_CONSORTIUM,
			[934] = L.FACTION_THE_SCRYERS,
			[935] = L.FACTION_THE_SHATAR,
			[942] = L.FACTION_CENARION_EXPEDITION,
			[967] = L.FACTION_THE_VIOLET_EYE,
			[970] = L.FACTION_SPOREGGAR,
			[989] = L.FACTION_KEEPERS_OF_TIME,
			[990] = L.FACTION_THE_SCALE_OF_THE_SANDS,
			[1011] = L.FACTION_LOWER_CITY,
			[1012] = L.FACTION_ASHTONGUE_DEATHSWORN,
			[1015] = L.FACTION_NETHERWING,
			[1031] = L.FACTION_SHATARI_SKYGUARD,
			[1038] = L.FACTION_OGRILA,
			[1077] = L.FACTION_SHATTERED_SUN_OFFENSIVE,
		},
	},
	[EXPANSION_WRATH] = {
		[REACT_ALLIANCE] = {
			[1050] = L.FACTION_VALIANCE_EXPEDITION,
			[1094] = L.FACTION_THE_SILVER_COVENANT,
			[1126] = L.FACTION_THE_FROSTBORN,
		},
		[REACT_HORDE] = {
			[1052] = L.FACTION_HORDE_EXPEDITION,
			[1067] = L.FACTION_THE_HAND_OF_VENGEANCE,
			[1085] = L.FACTION_WARSONG_OFFENSIVE,
			[1124] = L.FACTION_THE_SUNREAVERS,
		},
		[REACT_NEUTRAL] = {
			[1064] = L.FACTION_THE_TAUNKA,
			[1068] = L.FACTION_EXPLORERS_LEAGUE,
			[1073] = L.FACTION_THE_KALUAK,
			[1090] = L.FACTION_KIRIN_TOR,
			[1091] = L.FACTION_THE_WYRMREST_ACCORD,
			[1098] = L.FACTION_KNIGHTS_OF_THE_EBON_BLADE,
			[1104] = L.FACTION_FRENZYHEART_TRIBE,
			[1105] = L.FACTION_THE_ORACLES,
			[1106] = L.FACTION_ARGENT_CRUSADE,
			[1119] = L.FACTION_THE_SONS_OF_HODIR,
		},
	},
	[EXPANSION_CATA] = {
		[REACT_HORDE] = {
			[1133] = L.FACTION_BILGEWATER_CARTEL,
			[1172] = L.FACTION_DRAGONMAW_CLAN,
			[1178] = L.FACTION_HELLSCREAMS_REACH,
		},
		[REACT_ALLIANCE] = {
			[1134] = L.FACTION_GILNEAS,
			[1174] = L.FACTION_WILDHAMMER_CLAN,
			[1177] = L.FACTION_BARADINS_WARDENS,
		},
		[REACT_NEUTRAL] = {
			[1135] = L.FACTION_THE_EARTHEN_RING,
			[1156] = L.FACTION_THE_ASHEN_VERDICT,
			[1158] = L.FACTION_GUARDIANS_OF_HYJAL,
			[1168] = L.FACTION_GUILD,
			[1171] = L.FACTION_THERAZANE,
			[1173] = L.FACTION_RAMKAHEN,
			[1204] = L.FACTION_AVENGERS_OF_HYJAL,
		},
	},
	[EXPANSION_MISTS] = {
		[REACT_NEUTRAL] = {
			[1216] = L.FACTION_SHANG_XIS_ACADEMY,
			[1269] = L.FACTION_GOLDEN_LOTUS,
			[1270] = L.FACTION_SHADOPAN,
			[1271] = L.FACTION_ORDER_OF_THE_CLOUD_SERPENT,
			[1272] = L.FACTION_THE_TILLERS,
			[1273] = L.FACTION_JOGU_THE_DRUNK,
			[1275] = L.FACTION_ELLA,
			[1276] = L.FACTION_OLD_HILLPAW,
			[1277] = L.FACTION_CHEE_CHEE,
			[1278] = L.FACTION_SHO,
			[1279] = L.FACTION_HAOHAN_MUDCLAW,
			[1280] = L.FACTION_TINA_MUDCLAW,
			[1281] = L.FACTION_GINA_MUDCLAW,
			[1282] = L.FACTION_FISH_FELLREED,
			[1283] = L.FACTION_FARMER_FUNG,
			[1302] = L.FACTION_THE_ANGLERS,
			[1336] = L.FACTION_THE_MANTID_SWARM,
			[1337] = L.FACTION_THE_KLAXXI,
			[1341] = L.FACTION_THE_AUGUST_CELESTIALS,
			[1345] = L.FACTION_THE_LOREWALKERS,
			[1358] = L.FACTION_NAT_PAGLE,
			[1359] = L.FACTION_THE_BLACK_PRINCE,
			[1435] = L.FACTION_SHADOPAN_ASSAULT,
			[1492] = L.FACTION_EMPEROR_SHAOHAO,
		},
		[REACT_HORDE] = {
			[1228] = L.FACTION_FOREST_HOZEN,
			[1352] = L.FACTION_HUOJIN_PANDAREN,
			[1375] = L.FACTION_DOMINANCE_OFFENSIVE,
			[1388] = L.FACTION_SUNREAVER_ONSLAUGHT,
		},
		[REACT_ALLIANCE] = {
			[1242] = L.FACTION_PEARLFIN_JINYU,
			[1353] = L.FACTION_TUSHUI_PANDAREN,
			[1376] = L.FACTION_OPERATION_SHIELDWALL,
			[1387] = L.FACTION_KIRIN_TOR_OFFENSIVE,
		},
	},
	[EXPANSION_WARLORDS] = {
		[REACT_HORDE] = {
			[1445] = L.FACTION_FROSTWOLF_ORCS,
			[1681] = L.FACTION_VOLJINS_SPEAR,
			[1708] = L.FACTION_LAUGHING_SKULL_ORCS,
			[1848] = L.FACTION_VOLJINS_HEADHUNTERS,
		},
		[REACT_NEUTRAL] = {
			[1515] = L.FACTION_ARAKKOA_OUTCASTS,
			[1711] = L.FACTION_STEAMWHEEDLE_PRESERVATION_SOCIETY,
			[1849] = L.FACTION_ORDER_OF_THE_AWAKENED,
			[1850] = L.FACTION_THE_SABERSTALKERS,
		},
		[REACT_ALLIANCE] = {
			[1682] = L.FACTION_WRYNNS_VANGUARD,
			[1710] = L.FACTION_SHATARI_DEFENSE,
			[1731] = L.FACTION_COUNCIL_OF_EXARCHS,
			[1847] = L.FACTION_HAND_OF_THE_PROPHET,
		},
	},
	[EXPANSION_LEGION] = {
		[REACT_NEUTRAL] = {
			[1828] = L.FACTION_HIGHMOUNTAIN_TRIBE,
			[1859] = L.FACTION_THE_NIGHTFALLEN,
			[1883] = L.FACTION_DREAMWEAVERS,
			[1894] = L.FACTION_THE_WARDENS,
			[1900] = L.FACTION_COURT_OF_FARONDIS,
			[1948] = L.FACTION_VALARJAR,
			[1975] = L.FACTION_CONJURER_MARGOSS,
			[1984] = L.FACTION_THE_FIRST_RESPONDERS,
		},
	},
}