--[[
	BetterRep (C) Kruithne <kruithne@gmail.com>
	Licensed under GNU General Public Licence version 3.
	
	https://github.com/Kruithne/BetterRep

	localization/zhCN.lua - Chinese (Simplified) localization strings.
]]


if GetLocale() == "zhCN" then
	local L = BetterRep.L;

	-- Generic
	L["HEADER_REPUTATION"] = "声誉";

	-- Factions
	L["FACTION_BOOTY_BAY"] = "藏宝海湾";
	L["FACTION_IRONFORGE"] = "铁炉堡";
	L["FACTION_GNOMEREGAN"] = "诺莫瑞根";
	L["FACTION_THORIUM_BROTHERHOOD"] = "瑟银兄弟会";
	L["FACTION_UNDERCITY"] = "幽暗城";
	L["FACTION_DARNASSUS"] = "达纳苏斯";
	L["FACTION_SYNDICATE"] = "辛迪加";
	L["FACTION_STORMWIND"] = "暴风城";
	L["FACTION_ORGRIMMAR"] = "奥格瑞玛";
	L["FACTION_THUNDER_BLUFF"] = "雷霆崖";
	L["FACTION_BLOODSAIL_BUCCANEERS"] = "血帆海盗";
	L["FACTION_GELKIS_CLAN_CENTAUR"] = "吉尔吉斯半人马";
	L["FACTION_MAGRAM_CLAN_CENTAUR"] = "玛格拉姆半人马";
	L["FACTION_ZANDALAR_TRIBE"] = "赞达拉部族";
	L["FACTION_RAVENHOLDT"] = "拉文霍德";
	L["FACTION_GADGETZAN"] = "加基森";
	L["FACTION_RATCHET"] = "棘齿城";
	L["FACTION_THE_LEAGUE_OF_ARATHOR"] = "阿拉索联军";
	L["FACTION_THE_DEFILERS"] = "污染者";
	L["FACTION_ARGENT_DAWN"] = "银色黎明";
	L["FACTION_DARKSPEAR_TROLLS"] = "暗矛巨魔";
	L["FACTION_TIMBERMAW_HOLD"] = "木喉要塞";
	L["FACTION_EVERLOOK"] = "永望镇";
	L["FACTION_WINTERSABER_TRAINERS"] = "冬刃豹训练师";
	L["FACTION_CENARION_CIRCLE"] = "塞纳里奥议会";
	L["FACTION_FROSTWOLF_CLAN"] = "霜狼氏族";
	L["FACTION_STORMPIKE_GUARD"] = "雷矛卫队";
	L["FACTION_HYDRAXIAN_WATERLORDS"] = "海达希亚水元素";
	L["FACTION_SHENDRALAR"] = "辛德拉";
	L["FACTION_WARSONG_OUTRIDERS"] = "战歌氏族";
	L["FACTION_SILVERWING_SENTINELS"] = "银翼要塞";
	L["FACTION_DARKMOON_FAIRE"] = "暗月马戏团";
	L["FACTION_BROOD_OF_NOZDORMU"] = "诺兹多姆的子嗣";
	L["FACTION_SILVERMOON_CITY"] = "银月城";
	L["FACTION_TRANQUILLIEN"] = "塔奎林";
	L["FACTION_EXODAR"] = "埃索达";
	L["FACTION_THE_ALDOR"] = "奥尔多";
	L["FACTION_THE_CONSORTIUM"] = "星界财团";
	L["FACTION_THE_SCRYERS"] = "占星者";
	L["FACTION_THE_SHATAR"] = "沙塔尔";
	L["FACTION_THE_MAGHAR"] = "玛格汉";
	L["FACTION_CENARION_EXPEDITION"] = "塞纳里奥远征队";
	L["FACTION_HONOR_HOLD"] = "荣耀堡";
	L["FACTION_THRALLMAR"] = "萨尔玛";
	L["FACTION_THE_VIOLET_EYE"] = "紫罗兰之眼";
	L["FACTION_SPOREGGAR"] = "孢子村";
	L["FACTION_KURENAI"] = "库雷尼";
	L["FACTION_KEEPERS_OF_TIME"] = "时光守护者";
	L["FACTION_THE_SCALE_OF_THE_SANDS"] = "流沙之鳞";
	L["FACTION_LOWER_CITY"] = "贫民窟";
	L["FACTION_ASHTONGUE_DEATHSWORN"] = "灰舌死誓者";
	L["FACTION_NETHERWING"] = "灵翼之龙";
	L["FACTION_SHATARI_SKYGUARD"] = "沙塔尔天空卫队";
	L["FACTION_ALLIANCE_VANGUARD"] = "联盟先遣军";
	L["FACTION_OGRILA"] = "奥格瑞拉";
	L["FACTION_VALIANCE_EXPEDITION"] = "无畏远征军";
	L["FACTION_HORDE_EXPEDITION"] = "部落先遣军";
	L["FACTION_THE_TAUNKA"] = "牦牛人";
	L["FACTION_THE_HAND_OF_VENGEANCE"] = "复仇之手";
	L["FACTION_EXPLORERS_LEAGUE"] = "探险者协会";
	L["FACTION_THE_KALUAK"] = "卡鲁亚克";
	L["FACTION_SHATTERED_SUN_OFFENSIVE"] = "破碎残阳";
	L["FACTION_WARSONG_OFFENSIVE"] = "战歌远征军";
	L["FACTION_KIRIN_TOR"] = "肯瑞托";
	L["FACTION_THE_WYRMREST_ACCORD"] = "龙眠联军";
	L["FACTION_THE_SILVER_COVENANT"] = "银色盟约";
	L["FACTION_KNIGHTS_OF_THE_EBON_BLADE"] = "黑锋骑士团";
	L["FACTION_FRENZYHEART_TRIBE"] = "狂心氏族";
	L["FACTION_THE_ORACLES"] = "神谕者";
	L["FACTION_ARGENT_CRUSADE"] = "银色北伐军";
	L["FACTION_THE_SONS_OF_HODIR"] = "霍迪尔之子";
	L["FACTION_THE_SUNREAVERS"] = "夺日者";
	L["FACTION_THE_FROSTBORN"] = "霜脉矮人";
	L["FACTION_BILGEWATER_CARTEL"] = "锈水财阀";
	L["FACTION_GILNEAS"] = "吉尔尼斯";
	L["FACTION_THE_EARTHEN_RING"] = "大地之环";
	L["FACTION_THE_ASHEN_VERDICT"] = "灰烬审判军";
	L["FACTION_GUARDIANS_OF_HYJAL"] = "海加尔守护者";
	L["FACTION_GUILD"] = "公会";
	L["FACTION_THERAZANE"] = "塞拉赞恩";
	L["FACTION_DRAGONMAW_CLAN"] = "龙喉氏族";
	L["FACTION_RAMKAHEN"] = "拉穆卡恒";
	L["FACTION_WILDHAMMER_CLAN"] = "蛮锤部族";
	L["FACTION_BARADINS_WARDENS"] = "巴拉丁典狱官";
	L["FACTION_HELLSCREAMS_REACH"] = "地狱咆哮近卫军";
	L["FACTION_AVENGERS_OF_HYJAL"] = "海加尔复仇者";
	L["FACTION_SHANG_XIS_ACADEMY"] = "尚喜武院";
	L["FACTION_FOREST_HOZEN"] = "森林猢狲";
	L["FACTION_PEARLFIN_JINYU"] = "珠鳍锦鱼人";
	L["FACTION_GOLDEN_LOTUS"] = "金莲教";
	L["FACTION_SHADOPAN"] = "影踪派";
	L["FACTION_ORDER_OF_THE_CLOUD_SERPENT"] = "云端翔龙骑士团";
	L["FACTION_THE_TILLERS"] = "阡陌客";
	L["FACTION_JOGU_THE_DRUNK"] = "醉鬼贾古";
	L["FACTION_ELLA"] = "艾拉";
	L["FACTION_OLD_HILLPAW"] = "老农山掌";
	L["FACTION_CHEE_CHEE"] = "吱吱";
	L["FACTION_SHO"] = "阿烁";
	L["FACTION_HAOHAN_MUDCLAW"] = "郝瀚·泥爪";
	L["FACTION_TINA_MUDCLAW"] = "迪娜·泥爪";
	L["FACTION_GINA_MUDCLAW"] = "吉娜·泥爪";
	L["FACTION_FISH_FELLREED"] = "玉儿·采苇";
	L["FACTION_FARMER_FUNG"] = "农夫老方";
	L["FACTION_THE_ANGLERS"] = "垂钓翁";
	L["FACTION_THE_MANTID_SWARM"] = "螳螂妖虫群";
	L["FACTION_THE_KLAXXI"] = "卡拉克西";
	L["FACTION_THE_AUGUST_CELESTIALS"] = "至尊天神";
	L["FACTION_THE_LOREWALKERS"] = "游学者";
	L["FACTION_HUOJIN_PANDAREN"] = "火金派熊猫人";
	L["FACTION_TUSHUI_PANDAREN"] = "土水派熊猫人";
	L["FACTION_NAT_PAGLE"] = "纳特·帕格";
	L["FACTION_THE_BLACK_PRINCE"] = "黑王子";
	L["FACTION_DOMINANCE_OFFENSIVE"] = "统御先锋军";
	L["FACTION_OPERATION_SHIELDWALL"] = "神盾守备军";
	L["FACTION_KIRIN_TOR_OFFENSIVE"] = "肯瑞托远征军";
	L["FACTION_SUNREAVER_ONSLAUGHT"] = "夺日者先锋军";
	L["FACTION_SHADOPAN_ASSAULT"] = "影踪突袭营";
	L["FACTION_FROSTWOLF_ORCS"] = "霜狼兽人";
	L["FACTION_EMPEROR_SHAOHAO"] = "皇帝少昊";
	L["FACTION_ARAKKOA_OUTCASTS"] = "鸦人流亡者";
	L["FACTION_VOLJINS_SPEAR"] = "沃金之矛";
	L["FACTION_WRYNNS_VANGUARD"] = "乌瑞恩先锋军";
	L["FACTION_LAUGHING_SKULL_ORCS"] = "嘲颅兽人";
	L["FACTION_SHATARI_DEFENSE"] = "沙塔尔防御者";
	L["FACTION_STEAMWHEEDLE_PRESERVATION_SOCIETY"] = "热砂保护协会";
	L["FACTION_COUNCIL_OF_EXARCHS"] = "主教议会";
	L["FACTION_HIGHMOUNTAIN_TRIBE"] = "高岭部族";
	L["FACTION_HAND_OF_THE_PROPHET"] = "先知之手";
	L["FACTION_VOLJINS_HEADHUNTERS"] = "沃金之锋";
	L["FACTION_ORDER_OF_THE_AWAKENED"] = "觉醒教派";
	L["FACTION_THE_SABERSTALKERS"] = "刃牙追猎者";
	L["FACTION_THE_NIGHTFALLEN"] = "堕夜精灵";
	L["FACTION_DREAMWEAVERS"] = "织梦者";
	L["FACTION_THE_WARDENS"] = "守望者";
	L["FACTION_COURT_OF_FARONDIS"] = "法罗迪斯宫廷";
	L["FACTION_VALARJAR"] = "瓦拉加尔";
	L["FACTION_CONJURER_MARGOSS"] = "咒法师马戈斯";
	L["FACTION_THE_FIRST_RESPONDERS"] = "急救队";
end