--[[
	BetterRep (C) Kruithne <kruithne@gmail.com>
	Licensed under GNU General Public Licence version 3.
	
	https://github.com/Kruithne/BetterRep

	localization/zhTW.lua - Chinese (Traditional) localization strings.
]]


if GetLocale() == "zhTW" then
	local L = BetterRep.L;

	-- Generic
	L["HEADER_REPUTATION"] = "聲望";

	-- Expansion titles.
	L["EXPANSION_VANILLA"] = "艾澤拉斯";
	L["EXPANSION_TBC"] = "燃燒的遠征";
	L["EXPANSION_WOTLK"] = "巫妖王之怒";
	L["EXPANSION_CATA"] = "浩劫與重生";
	L["EXPANSION_MISTS"] = "潘達利亞之謎";
	L["EXPANSION_WARLORDS"] = "德拉諾之霸";
	L["EXPANSION_LEGION"] = "《軍臨天下》";

	-- Factions
	L["FACTION_BOOTY_BAY"] = "藏寶海灣";
	L["FACTION_IRONFORGE"] = "鐵爐堡";
	L["FACTION_GNOMEREGAN"] = "諾姆瑞根";
	L["FACTION_THORIUM_BROTHERHOOD"] = "瑟銀兄弟會";
	L["FACTION_UNDERCITY"] = "幽暗城";
	L["FACTION_DARNASSUS"] = "達納蘇斯";
	L["FACTION_SYNDICATE"] = "辛迪加";
	L["FACTION_STORMWIND"] = "暴風城";
	L["FACTION_ORGRIMMAR"] = "奧格瑪";
	L["FACTION_THUNDER_BLUFF"] = "雷霆崖";
	L["FACTION_BLOODSAIL_BUCCANEERS"] = "血帆海盜";
	L["FACTION_GELKIS_CLAN_CENTAUR"] = "吉爾吉斯半人馬";
	L["FACTION_MAGRAM_CLAN_CENTAUR"] = "瑪格拉姆半人馬";
	L["FACTION_ZANDALAR_TRIBE"] = "贊達拉部族";
	L["FACTION_RAVENHOLDT"] = "拉文霍德";
	L["FACTION_GADGETZAN"] = "加基森";
	L["FACTION_RATCHET"] = "棘齒城";
	L["FACTION_THE_LEAGUE_OF_ARATHOR"] = "阿拉索聯軍";
	L["FACTION_THE_DEFILERS"] = "污染者";
	L["FACTION_ARGENT_DAWN"] = "銀色黎明";
	L["FACTION_DARKSPEAR_TROLLS"] = "暗矛食人妖";
	L["FACTION_TIMBERMAW_HOLD"] = "木喉要塞";
	L["FACTION_EVERLOOK"] = "永望鎮";
	L["FACTION_WINTERSABER_TRAINERS"] = "冬刃豹訓練師";
	L["FACTION_CENARION_CIRCLE"] = "塞納里奧議會";
	L["FACTION_FROSTWOLF_CLAN"] = "霜狼氏族";
	L["FACTION_STORMPIKE_GUARD"] = "雷矛衛隊";
	L["FACTION_HYDRAXIAN_WATERLORDS"] = "海達希亞水元素";
	L["FACTION_SHENDRALAR"] = "辛德拉";
	L["FACTION_WARSONG_OUTRIDERS"] = "戰歌先遣騎";
	L["FACTION_SILVERWING_SENTINELS"] = "銀翼哨兵";
	L["FACTION_DARKMOON_FAIRE"] = "暗月馬戲團";
	L["FACTION_BROOD_OF_NOZDORMU"] = "諾茲多姆的子嗣";
	L["FACTION_SILVERMOON_CITY"] = "銀月城";
	L["FACTION_TRANQUILLIEN"] = "安寧地";
	L["FACTION_EXODAR"] = "艾克索達";
	L["FACTION_THE_ALDOR"] = "奧多爾";
	L["FACTION_THE_CONSORTIUM"] = "聯合團";
	L["FACTION_THE_SCRYERS"] = "占卜者";
	L["FACTION_THE_SHATAR"] = "薩塔";
	L["FACTION_THE_MAGHAR"] = "瑪格哈";
	L["FACTION_CENARION_EXPEDITION"] = "塞納里奧遠征隊";
	L["FACTION_HONOR_HOLD"] = "榮譽堡";
	L["FACTION_THRALLMAR"] = "索爾瑪";
	L["FACTION_THE_VIOLET_EYE"] = "紫羅蘭之眼";
	L["FACTION_SPOREGGAR"] = "斯博格爾";
	L["FACTION_KURENAI"] = "卡爾奈";
	L["FACTION_KEEPERS_OF_TIME"] = "時光守望者";
	L["FACTION_THE_SCALE_OF_THE_SANDS"] = "流沙之鱗";
	L["FACTION_LOWER_CITY"] = "陰鬱城";
	L["FACTION_ASHTONGUE_DEATHSWORN"] = "灰舌死亡誓言者";
	L["FACTION_NETHERWING"] = "虛空之翼";
	L["FACTION_SHATARI_SKYGUARD"] = "薩塔禦天者";
	L["FACTION_ALLIANCE_VANGUARD"] = "聯盟先鋒";
	L["FACTION_OGRILA"] = "歐格利拉";
	L["FACTION_VALIANCE_EXPEDITION"] = "驍勇遠征軍";
	L["FACTION_HORDE_EXPEDITION"] = "部落遠征軍";
	L["FACTION_THE_TAUNKA"] = "坦卡族";
	L["FACTION_THE_HAND_OF_VENGEANCE"] = "復仇之手";
	L["FACTION_EXPLORERS_LEAGUE"] = "探險者協會";
	L["FACTION_THE_KALUAK"] = "卡魯耶克";
	L["FACTION_SHATTERED_SUN_OFFENSIVE"] = "破碎之日進攻部隊";
	L["FACTION_WARSONG_OFFENSIVE"] = "戰歌進攻部隊";
	L["FACTION_KIRIN_TOR"] = "祈倫托";
	L["FACTION_THE_WYRMREST_ACCORD"] = "龍眠協調者";
	L["FACTION_THE_SILVER_COVENANT"] = "白銀誓盟";
	L["FACTION_KNIGHTS_OF_THE_EBON_BLADE"] = "黯刃騎士團";
	L["FACTION_FRENZYHEART_TRIBE"] = "狂心部族";
	L["FACTION_THE_ORACLES"] = "神諭者";
	L["FACTION_ARGENT_CRUSADE"] = "銀白十字軍";
	L["FACTION_THE_SONS_OF_HODIR"] = "霍迪爾之子";
	L["FACTION_THE_SUNREAVERS"] = "奪日者";
	L["FACTION_THE_FROSTBORN"] = "霜誕矮人";
	L["FACTION_BILGEWATER_CARTEL"] = "污水企業聯合";
	L["FACTION_GILNEAS"] = "吉爾尼斯";
	L["FACTION_THE_EARTHEN_RING"] = "陶土議會";
	L["FACTION_THE_ASHEN_VERDICT"] = "灰燼裁決軍";
	L["FACTION_GUARDIANS_OF_HYJAL"] = "海加爾守護者";
	L["FACTION_GUILD"] = "公會";
	L["FACTION_THERAZANE"] = "瑟拉贊恩";
	L["FACTION_DRAGONMAW_CLAN"] = "龍喉氏族";
	L["FACTION_RAMKAHEN"] = "蘭姆卡韓";
	L["FACTION_WILDHAMMER_CLAN"] = "蠻錘氏族";
	L["FACTION_BARADINS_WARDENS"] = "巴拉丁鐵衛";
	L["FACTION_HELLSCREAMS_REACH"] = "地獄吼先鋒";
	L["FACTION_AVENGERS_OF_HYJAL"] = "海加爾復仇者";
	L["FACTION_SHANG_XIS_ACADEMY"] = "尚羲學院";
	L["FACTION_FOREST_HOZEN"] = "森林猴人";
	L["FACTION_PEARLFIN_JINYU"] = "珠鰭錦魚人";
	L["FACTION_GOLDEN_LOTUS"] = "金蓮會";
	L["FACTION_SHADOPAN"] = "影潘";
	L["FACTION_ORDER_OF_THE_CLOUD_SERPENT"] = "雲蛟衛";
	L["FACTION_THE_TILLERS"] = "耕者工會";
	L["FACTION_JOGU_THE_DRUNK"] = "『酒鬼』酒骨";
	L["FACTION_ELLA"] = "艾拉";
	L["FACTION_OLD_HILLPAW"] = "老丘爪";
	L["FACTION_CHEE_CHEE"] = "奇奇";
	L["FACTION_SHO"] = "阿秀";
	L["FACTION_HAOHAN_MUDCLAW"] = "好漢·泥爪";
	L["FACTION_TINA_MUDCLAW"] = "蒂娜·泥爪";
	L["FACTION_GINA_MUDCLAW"] = "吉娜·泥爪";
	L["FACTION_FISH_FELLREED"] = "小魚·跌蘆";
	L["FACTION_FARMER_FUNG"] = "農夫老豐";
	L["FACTION_THE_ANGLERS"] = "釣手隊";
	L["FACTION_THE_MANTID_SWARM"] = "螳族";
	L["FACTION_THE_KLAXXI"] = "卡拉西";
	L["FACTION_THE_AUGUST_CELESTIALS"] = "聖獸天尊";
	L["FACTION_THE_LOREWALKERS"] = "博學行者";
	L["FACTION_HUOJIN_PANDAREN"] = "火金熊貓人";
	L["FACTION_TUSHUI_PANDAREN"] = "土水熊貓人";
	L["FACTION_NAT_PAGLE"] = "納特·帕格";
	L["FACTION_THE_BLACK_PRINCE"] = "黑龍王子";
	L["FACTION_DOMINANCE_OFFENSIVE"] = "制霸先鋒軍";
	L["FACTION_OPERATION_SHIELDWALL"] = "鐵壁特遣行動";
	L["FACTION_KIRIN_TOR_OFFENSIVE"] = "祈倫托先遣軍";
	L["FACTION_SUNREAVER_ONSLAUGHT"] = "奪日者先鋒軍";
	L["FACTION_SHADOPAN_ASSAULT"] = "影潘之襲";
	L["FACTION_FROSTWOLF_ORCS"] = "霜狼獸人";
	L["FACTION_EMPEROR_SHAOHAO"] = "紹昊大帝";
	L["FACTION_ARAKKOA_OUTCASTS"] = "阿拉卡流亡者";
	L["FACTION_VOLJINS_SPEAR"] = "沃金之矛";
	L["FACTION_WRYNNS_VANGUARD"] = "烏瑞恩先鋒";
	L["FACTION_LAUGHING_SKULL_ORCS"] = "獰笑骷髏獸人";
	L["FACTION_SHATARI_DEFENSE"] = "撒塔斯守軍";
	L["FACTION_STEAMWHEEDLE_PRESERVATION_SOCIETY"] = "熱砂保護協會";
	L["FACTION_COUNCIL_OF_EXARCHS"] = "主教議會";
	L["FACTION_HIGHMOUNTAIN_TRIBE"] = "高嶺部族";
	L["FACTION_HAND_OF_THE_PROPHET"] = "預言者之手";
	L["FACTION_VOLJINS_HEADHUNTERS"] = "沃金獵頭者";
	L["FACTION_ORDER_OF_THE_AWAKENED"] = "覺醒者衛隊";
	L["FACTION_THE_SABERSTALKERS"] = "劍齒潛獵者";
	L["FACTION_THE_NIGHTFALLEN"] = "夜落精靈";
	L["FACTION_DREAMWEAVERS"] = "織夢者";
	L["FACTION_THE_WARDENS"] = "看守者";
	L["FACTION_COURT_OF_FARONDIS"] = "法隆迪斯廷衛";
	L["FACTION_VALARJAR"] = "華爾拉亞";
	L["FACTION_CONJURER_MARGOSS"] = "咒術師瑪苟斯";
	L["FACTION_THE_FIRST_RESPONDERS"] = "第一應援者";
end